/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author aaron
 */
public class VentanaReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    public JButton getVentanaReporte_BntActualizar() {
        return VentanaReporte_BntActualizar;
    }

    public void setVentanaReporte_BntActualizar(JButton VentanaReporte_BntActualizar) {
        this.VentanaReporte_BntActualizar = VentanaReporte_BntActualizar;
    }

    public JButton getVentanaReporte_BntAnular() {
        return VentanaReporte_BntAnular;
    }

    public void setVentanaReporte_BntAnular(JButton VentanaReporte_BntAnular) {
        this.VentanaReporte_BntAnular = VentanaReporte_BntAnular;
    }

    public JButton getVentanaReporte_BntAplicarFiltro() {
        return VentanaReporte_BntAplicarFiltro;
    }

    public void setVentanaReporte_BntAplicarFiltro(JButton VentanaReporte_BntAplicarFiltro) {
        this.VentanaReporte_BntAplicarFiltro = VentanaReporte_BntAplicarFiltro;
    }

    public JButton getVentanaReporte_BntEditar() {
        return VentanaReporte_BntEditar;
    }

    public void setVentanaReporte_BntEditar(JButton VentanaReporte_BntEditar) {
        this.VentanaReporte_BntEditar = VentanaReporte_BntEditar;
    }

    public JButton getVentanaReporte_BntNevo() {
        return VentanaReporte_BntNevo;
    }

    public void setVentanaReporte_BntNevo(JButton VentanaReporte_BntNevo) {
        this.VentanaReporte_BntNevo = VentanaReporte_BntNevo;
    }

    public JButton getVentanaReporte_BntVer() {
        return VentanaReporte_BntVer;
    }

    public void setVentanaReporte_BntVer(JButton VentanaReporte_BntVer) {
        this.VentanaReporte_BntVer = VentanaReporte_BntVer;
    }

    public JComboBox<String> getVentanaReporte_ComboActivo() {
        return VentanaReporte_ComboActivo;
    }

    public void setVentanaReporte_ComboActivo(JComboBox<String> VentanaReporte_ComboActivo) {
        this.VentanaReporte_ComboActivo = VentanaReporte_ComboActivo;
    }

    public JComboBox<String> getVentanaReporte_ComboAplicarIva() {
        return VentanaReporte_ComboAplicarIva;
    }

    public void setVentanaReporte_ComboAplicarIva(JComboBox<String> VentanaReporte_ComboAplicarIva) {
        this.VentanaReporte_ComboAplicarIva = VentanaReporte_ComboAplicarIva;
    }

    public JComboBox<String> getVentanaReporte_ComboBodega() {
        return VentanaReporte_ComboBodega;
    }

    public void setVentanaReporte_ComboBodega(JComboBox<String> VentanaReporte_ComboBodega) {
        this.VentanaReporte_ComboBodega = VentanaReporte_ComboBodega;
    }

    public JComboBox<String> getVentanaReporte_ComboMarca() {
        return VentanaReporte_ComboMarca;
    }

    public void setVentanaReporte_ComboMarca(JComboBox<String> VentanaReporte_ComboMarca) {
        this.VentanaReporte_ComboMarca = VentanaReporte_ComboMarca;
    }

    public JDateChooser getVentanaReporte_JDateFechaCorte() {
        return VentanaReporte_JDateFechaCorte;
    }

    public void setVentanaReporte_JDateFechaCorte(JDateChooser VentanaReporte_JDateFechaCorte) {
        this.VentanaReporte_JDateFechaCorte = VentanaReporte_JDateFechaCorte;
    }

    public JPanel getVentanaReporte_PanelFiltro() {
        return VentanaReporte_PanelFiltro;
    }

    public void setVentanaReporte_PanelFiltro(JPanel VentanaReporte_PanelFiltro) {
        this.VentanaReporte_PanelFiltro = VentanaReporte_PanelFiltro;
    }

    public JPanel getVentanaReporte_PanelStock() {
        return VentanaReporte_PanelStock;
    }

    public void setVentanaReporte_PanelStock(JPanel VentanaReporte_PanelStock) {
        this.VentanaReporte_PanelStock = VentanaReporte_PanelStock;
    }

    public JTable getVentanaReporte_tablaGeneral() {
        return VentanaReporte_tablaGeneral;
    }

    public void setVentanaReporte_tablaGeneral(JTable VentanaReporte_tablaGeneral) {
        this.VentanaReporte_tablaGeneral = VentanaReporte_tablaGeneral;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        VentanaReporte_BntNevo = new javax.swing.JButton();
        VentanaReporte_BntEditar = new javax.swing.JButton();
        VentanaReporte_BntAnular = new javax.swing.JButton();
        VentanaReporte_BntVer = new javax.swing.JButton();
        VentanaReporte_PanelStock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VentanaReporte_JDateFechaCorte = new com.toedter.calendar.JDateChooser();
        VentanaReporte_ComboMarca = new javax.swing.JComboBox<>();
        VentanaReporte_ComboBodega = new javax.swing.JComboBox<>();
        VentanaReporte_ComboAplicarIva = new javax.swing.JComboBox<>();
        VentanaReporte_ComboActivo = new javax.swing.JComboBox<>();
        VentanaReporte_PanelFiltro = new javax.swing.JPanel();
        VentanaReporte_BntAplicarFiltro = new javax.swing.JButton();
        VentanaReporte_BntActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VentanaReporte_tablaGeneral = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        VentanaReporte_BntNevo.setText("Nuevo");

        VentanaReporte_BntEditar.setText("Editar");

        VentanaReporte_BntAnular.setText("Anular");

        VentanaReporte_BntVer.setText("Ver Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(VentanaReporte_BntNevo)
                .addGap(18, 18, 18)
                .addComponent(VentanaReporte_BntEditar)
                .addGap(18, 18, 18)
                .addComponent(VentanaReporte_BntAnular)
                .addGap(18, 18, 18)
                .addComponent(VentanaReporte_BntVer)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VentanaReporte_BntNevo)
                    .addComponent(VentanaReporte_BntEditar)
                    .addComponent(VentanaReporte_BntAnular)
                    .addComponent(VentanaReporte_BntVer))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 954, -1));

        VentanaReporte_PanelStock.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_PanelStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte de Stock"));
        VentanaReporte_PanelStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha de Corte:");
        VentanaReporte_PanelStock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 24, -1, -1));

        jLabel2.setText("Marca:");
        VentanaReporte_PanelStock.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setText("Bodega:");
        VentanaReporte_PanelStock.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setText("Aplica IVA:");
        VentanaReporte_PanelStock.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel5.setText("Activo:");
        VentanaReporte_PanelStock.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        VentanaReporte_JDateFechaCorte.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_JDateFechaCorte.setForeground(new java.awt.Color(0, 0, 0));
        VentanaReporte_PanelStock.add(VentanaReporte_JDateFechaCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, -1));

        VentanaReporte_ComboMarca.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_ComboMarca.setForeground(new java.awt.Color(0, 0, 0));
        VentanaReporte_ComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        VentanaReporte_PanelStock.add(VentanaReporte_ComboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, -1));

        VentanaReporte_ComboBodega.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_ComboBodega.setForeground(new java.awt.Color(0, 0, 0));
        VentanaReporte_ComboBodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MATRIZ CUENCA" }));
        VentanaReporte_PanelStock.add(VentanaReporte_ComboBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, -1));

        VentanaReporte_ComboAplicarIva.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_ComboAplicarIva.setForeground(new java.awt.Color(0, 0, 0));
        VentanaReporte_ComboAplicarIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SI", "NO" }));
        VentanaReporte_PanelStock.add(VentanaReporte_ComboAplicarIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 190, -1));

        VentanaReporte_ComboActivo.setBackground(new java.awt.Color(255, 255, 255));
        VentanaReporte_ComboActivo.setForeground(new java.awt.Color(0, 0, 0));
        VentanaReporte_ComboActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SI", "NO" }));
        VentanaReporte_ComboActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaReporte_ComboActivoActionPerformed(evt);
            }
        });
        VentanaReporte_PanelStock.add(VentanaReporte_ComboActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 190, -1));

        jPanel2.add(VentanaReporte_PanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 950, 120));

        VentanaReporte_PanelFiltro.setBackground(new java.awt.Color(255, 51, 51));

        VentanaReporte_BntAplicarFiltro.setText("Aplicar Filtros");

        VentanaReporte_BntActualizar.setText("Actualizar");

        javax.swing.GroupLayout VentanaReporte_PanelFiltroLayout = new javax.swing.GroupLayout(VentanaReporte_PanelFiltro);
        VentanaReporte_PanelFiltro.setLayout(VentanaReporte_PanelFiltroLayout);
        VentanaReporte_PanelFiltroLayout.setHorizontalGroup(
            VentanaReporte_PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaReporte_PanelFiltroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(VentanaReporte_BntAplicarFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentanaReporte_BntActualizar)
                .addContainerGap(735, Short.MAX_VALUE))
        );
        VentanaReporte_PanelFiltroLayout.setVerticalGroup(
            VentanaReporte_PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaReporte_PanelFiltroLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(VentanaReporte_PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VentanaReporte_BntAplicarFiltro)
                    .addComponent(VentanaReporte_BntActualizar))
                .addContainerGap())
        );

        jPanel2.add(VentanaReporte_PanelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 954, 50));

        VentanaReporte_tablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Item", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(VentanaReporte_tablaGeneral);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 950, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentanaReporte_ComboActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaReporte_ComboActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentanaReporte_ComboActivoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaReportes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VentanaReporte_BntActualizar;
    private javax.swing.JButton VentanaReporte_BntAnular;
    private javax.swing.JButton VentanaReporte_BntAplicarFiltro;
    private javax.swing.JButton VentanaReporte_BntEditar;
    private javax.swing.JButton VentanaReporte_BntNevo;
    private javax.swing.JButton VentanaReporte_BntVer;
    private javax.swing.JComboBox<String> VentanaReporte_ComboActivo;
    private javax.swing.JComboBox<String> VentanaReporte_ComboAplicarIva;
    private javax.swing.JComboBox<String> VentanaReporte_ComboBodega;
    private javax.swing.JComboBox<String> VentanaReporte_ComboMarca;
    private com.toedter.calendar.JDateChooser VentanaReporte_JDateFechaCorte;
    private javax.swing.JPanel VentanaReporte_PanelFiltro;
    private javax.swing.JPanel VentanaReporte_PanelStock;
    private javax.swing.JTable VentanaReporte_tablaGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
