/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author aaron
 */
public class VentanaCambioPlan extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCambioPlan
     */
    public VentanaCambioPlan() {
        initComponents();
    }

    public JButton getVentanaCambioPlanBnt_Actualizar() {
        return VentanaCambioPlanBnt_Actualizar;
    }

    public void setVentanaCambioPlanBnt_Actualizar(JButton VentanaCambioPlanBnt_Actualizar) {
        this.VentanaCambioPlanBnt_Actualizar = VentanaCambioPlanBnt_Actualizar;
    }

    public JButton getVentanaCambioPlanBnt_Anular() {
        return VentanaCambioPlanBnt_Anular;
    }

    public void setVentanaCambioPlanBnt_Anular(JButton VentanaCambioPlanBnt_Anular) {
        this.VentanaCambioPlanBnt_Anular = VentanaCambioPlanBnt_Anular;
    }

    public JButton getVentanaCambioPlanBnt_Aplicar() {
        return VentanaCambioPlanBnt_Aplicar;
    }

    public void setVentanaCambioPlanBnt_Aplicar(JButton VentanaCambioPlanBnt_Aplicar) {
        this.VentanaCambioPlanBnt_Aplicar = VentanaCambioPlanBnt_Aplicar;
    }

    public JButton getVentanaCambioPlanBnt_Editar() {
        return VentanaCambioPlanBnt_Editar;
    }

    public void setVentanaCambioPlanBnt_Editar(JButton VentanaCambioPlanBnt_Editar) {
        this.VentanaCambioPlanBnt_Editar = VentanaCambioPlanBnt_Editar;
    }

    public JButton getVentanaCambioPlanBnt_ImprimirSolicitud() {
        return VentanaCambioPlanBnt_ImprimirSolicitud;
    }

    public void setVentanaCambioPlanBnt_ImprimirSolicitud(JButton VentanaCambioPlanBnt_ImprimirSolicitud) {
        this.VentanaCambioPlanBnt_ImprimirSolicitud = VentanaCambioPlanBnt_ImprimirSolicitud;
    }

    public JButton getVentanaCambioPlanBnt_Nuevo() {
        return VentanaCambioPlanBnt_Nuevo;
    }

    public void setVentanaCambioPlanBnt_Nuevo(JButton VentanaCambioPlanBnt_Nuevo) {
        this.VentanaCambioPlanBnt_Nuevo = VentanaCambioPlanBnt_Nuevo;
    }

    public JButton getVentanaCambioPlanBnt_RestablecerFiltro() {
        return VentanaCambioPlanBnt_RestablecerFiltro;
    }

    public void setVentanaCambioPlanBnt_RestablecerFiltro(JButton VentanaCambioPlanBnt_RestablecerFiltro) {
        this.VentanaCambioPlanBnt_RestablecerFiltro = VentanaCambioPlanBnt_RestablecerFiltro;
    }

    public JDateChooser getVentanaCambioPlanJDate_Desde() {
        return VentanaCambioPlanJDate_Desde;
    }

    public void setVentanaCambioPlanJDate_Desde(JDateChooser VentanaCambioPlanJDate_Desde) {
        this.VentanaCambioPlanJDate_Desde = VentanaCambioPlanJDate_Desde;
    }

    public JDateChooser getVentanaCambioPlanJDate_Hasta() {
        return VentanaCambioPlanJDate_Hasta;
    }

    public void setVentanaCambioPlanJDate_Hasta(JDateChooser VentanaCambioPlanJDate_Hasta) {
        this.VentanaCambioPlanJDate_Hasta = VentanaCambioPlanJDate_Hasta;
    }

    public JPanel getVentanaCambioPlanPanelBoton_Nuevo() {
        return VentanaCambioPlanPanelBoton_Nuevo;
    }

    public void setVentanaCambioPlanPanelBoton_Nuevo(JPanel VentanaCambioPlanPanelBoton_Nuevo) {
        this.VentanaCambioPlanPanelBoton_Nuevo = VentanaCambioPlanPanelBoton_Nuevo;
    }

    public JPanel getVentanaCambioPlanPanelFecha() {
        return VentanaCambioPlanPanelFecha;
    }

    public void setVentanaCambioPlanPanelFecha(JPanel VentanaCambioPlanPanelFecha) {
        this.VentanaCambioPlanPanelFecha = VentanaCambioPlanPanelFecha;
    }

    public JPanel getVentanaCambioPlanPanel_Bnt_Aplicar() {
        return VentanaCambioPlanPanel_Bnt_Aplicar;
    }

    public void setVentanaCambioPlanPanel_Bnt_Aplicar(JPanel VentanaCambioPlanPanel_Bnt_Aplicar) {
        this.VentanaCambioPlanPanel_Bnt_Aplicar = VentanaCambioPlanPanel_Bnt_Aplicar;
    }

    public JPanel getVentanaCambioPlanPanel_Solicitud() {
        return VentanaCambioPlanPanel_Solicitud;
    }

    public void setVentanaCambioPlanPanel_Solicitud(JPanel VentanaCambioPlanPanel_Solicitud) {
        this.VentanaCambioPlanPanel_Solicitud = VentanaCambioPlanPanel_Solicitud;
    }

    public JTextField getVentanaCambioPlantxt_cliente() {
        return VentanaCambioPlantxt_cliente;
    }

    public void setVentanaCambioPlantxt_cliente(JTextField VentanaCambioPlantxt_cliente) {
        this.VentanaCambioPlantxt_cliente = VentanaCambioPlantxt_cliente;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VentanaCambioPlanPanelBoton_Nuevo = new javax.swing.JPanel();
        VentanaCambioPlanBnt_Nuevo = new javax.swing.JButton();
        VentanaCambioPlanBnt_Editar = new javax.swing.JButton();
        VentanaCambioPlanBnt_Anular = new javax.swing.JButton();
        VentanaCambioPlanBnt_ImprimirSolicitud = new javax.swing.JButton();
        VentanaCambioPlanPanel_Solicitud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VentanaCambioPlanPanelFecha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VentanaCambioPlanJDate_Desde = new com.toedter.calendar.JDateChooser();
        VentanaCambioPlanJDate_Hasta = new com.toedter.calendar.JDateChooser();
        VentanaCambioPlantxt_cliente = new javax.swing.JTextField();
        VentanaCambioPlanPanel_Bnt_Aplicar = new javax.swing.JPanel();
        VentanaCambioPlanBnt_Aplicar = new javax.swing.JButton();
        VentanaCambioPlanBnt_Actualizar = new javax.swing.JButton();
        VentanaCambioPlanBnt_RestablecerFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentanaCambioPlanPanelBoton_Nuevo.setBackground(new java.awt.Color(0, 153, 51));

        VentanaCambioPlanBnt_Nuevo.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_Nuevo.setText("Nuevo");

        VentanaCambioPlanBnt_Editar.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_Editar.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_Editar.setText("Editar");

        VentanaCambioPlanBnt_Anular.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_Anular.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_Anular.setText("Anular");

        VentanaCambioPlanBnt_ImprimirSolicitud.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_ImprimirSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_ImprimirSolicitud.setText("Imprimir Solicitud");

        javax.swing.GroupLayout VentanaCambioPlanPanelBoton_NuevoLayout = new javax.swing.GroupLayout(VentanaCambioPlanPanelBoton_Nuevo);
        VentanaCambioPlanPanelBoton_Nuevo.setLayout(VentanaCambioPlanPanelBoton_NuevoLayout);
        VentanaCambioPlanPanelBoton_NuevoLayout.setHorizontalGroup(
            VentanaCambioPlanPanelBoton_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCambioPlanPanelBoton_NuevoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(VentanaCambioPlanBnt_Nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VentanaCambioPlanBnt_Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VentanaCambioPlanBnt_Anular)
                .addGap(18, 18, 18)
                .addComponent(VentanaCambioPlanBnt_ImprimirSolicitud)
                .addContainerGap(578, Short.MAX_VALUE))
        );
        VentanaCambioPlanPanelBoton_NuevoLayout.setVerticalGroup(
            VentanaCambioPlanPanelBoton_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaCambioPlanBnt_Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VentanaCambioPlanBnt_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(VentanaCambioPlanBnt_Anular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VentanaCambioPlanBnt_ImprimirSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(VentanaCambioPlanPanelBoton_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 40));

        VentanaCambioPlanPanel_Solicitud.setBackground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanPanel_Solicitud.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitudes de cambio de plan"));
        VentanaCambioPlanPanel_Solicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cliente:");
        VentanaCambioPlanPanel_Solicitud.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));
        VentanaCambioPlanPanel_Solicitud.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        VentanaCambioPlanPanelFecha.setBackground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanPanelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Cambio"));
        VentanaCambioPlanPanelFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Desde:");
        VentanaCambioPlanPanelFecha.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 24, -1, -1));

        jLabel4.setText("Hasta:");
        VentanaCambioPlanPanelFecha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 60, -1, -1));

        VentanaCambioPlanJDate_Desde.setBackground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanPanelFecha.add(VentanaCambioPlanJDate_Desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 18, 260, 23));

        VentanaCambioPlanJDate_Hasta.setBackground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanPanelFecha.add(VentanaCambioPlanJDate_Hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 53, 261, 23));

        VentanaCambioPlanPanel_Solicitud.add(VentanaCambioPlanPanelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 18, 470, 90));
        VentanaCambioPlanPanel_Solicitud.add(VentanaCambioPlantxt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, -1));

        jPanel1.add(VentanaCambioPlanPanel_Solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 960, 120));

        VentanaCambioPlanPanel_Bnt_Aplicar.setBackground(new java.awt.Color(0, 153, 51));

        VentanaCambioPlanBnt_Aplicar.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_Aplicar.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_Aplicar.setText("Aplicar Filtros");

        VentanaCambioPlanBnt_Actualizar.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_Actualizar.setText("Actualizar");

        VentanaCambioPlanBnt_RestablecerFiltro.setBackground(new java.awt.Color(0, 204, 51));
        VentanaCambioPlanBnt_RestablecerFiltro.setForeground(new java.awt.Color(255, 255, 255));
        VentanaCambioPlanBnt_RestablecerFiltro.setText("Restablecer Filtros");

        javax.swing.GroupLayout VentanaCambioPlanPanel_Bnt_AplicarLayout = new javax.swing.GroupLayout(VentanaCambioPlanPanel_Bnt_Aplicar);
        VentanaCambioPlanPanel_Bnt_Aplicar.setLayout(VentanaCambioPlanPanel_Bnt_AplicarLayout);
        VentanaCambioPlanPanel_Bnt_AplicarLayout.setHorizontalGroup(
            VentanaCambioPlanPanel_Bnt_AplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCambioPlanPanel_Bnt_AplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentanaCambioPlanBnt_Aplicar)
                .addGap(18, 18, 18)
                .addComponent(VentanaCambioPlanBnt_Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VentanaCambioPlanBnt_RestablecerFiltro)
                .addContainerGap(592, Short.MAX_VALUE))
        );
        VentanaCambioPlanPanel_Bnt_AplicarLayout.setVerticalGroup(
            VentanaCambioPlanPanel_Bnt_AplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCambioPlanPanel_Bnt_AplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(VentanaCambioPlanBnt_Aplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(VentanaCambioPlanBnt_Actualizar)
                .addComponent(VentanaCambioPlanBnt_RestablecerFiltro))
        );

        jPanel1.add(VentanaCambioPlanPanel_Bnt_Aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 960, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Cedula", "Contrato", "Plan Antiguo", "Plan Nuevo", "Fecha de Creacion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 960, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaCambioPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaCambioPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaCambioPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaCambioPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaCambioPlan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VentanaCambioPlanBnt_Actualizar;
    private javax.swing.JButton VentanaCambioPlanBnt_Anular;
    private javax.swing.JButton VentanaCambioPlanBnt_Aplicar;
    private javax.swing.JButton VentanaCambioPlanBnt_Editar;
    private javax.swing.JButton VentanaCambioPlanBnt_ImprimirSolicitud;
    private javax.swing.JButton VentanaCambioPlanBnt_Nuevo;
    private javax.swing.JButton VentanaCambioPlanBnt_RestablecerFiltro;
    private com.toedter.calendar.JDateChooser VentanaCambioPlanJDate_Desde;
    private com.toedter.calendar.JDateChooser VentanaCambioPlanJDate_Hasta;
    private javax.swing.JPanel VentanaCambioPlanPanelBoton_Nuevo;
    private javax.swing.JPanel VentanaCambioPlanPanelFecha;
    private javax.swing.JPanel VentanaCambioPlanPanel_Bnt_Aplicar;
    private javax.swing.JPanel VentanaCambioPlanPanel_Solicitud;
    private javax.swing.JTextField VentanaCambioPlantxt_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
